package com.sigera.entidad;
// Generated 24/10/2015 08:59:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActividadesExtracurriculares generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDADES_EXTRACURRICULARES"
)
public class ActividadesExtracurriculares implements java.io.Serializable {

    private ActividadesExtracurricularesId id;
    private Profesor profesor;
    private String vcDireccion;
    private String vcReferencia;
    private int inNumeroContacto;
    private Date dtFechaInicio;
    private Date dtFechaRetorno;
    private Date dtFechaCreacion;
    private Date dtFechaModificacion;
    private Set<IncidenciasPorActividadesExtracurriculares> incidenciasPorActividadesExtracurriculareses = new HashSet(0);

    public ActividadesExtracurriculares() {
    }


    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idActividadesExtracurriculares", column = @Column(name = "ID_ACTIVIDADES_EXTRACURRICULARES", nullable = false)),
        @AttributeOverride(name = "idProfesor", column = @Column(name = "ID_PROFESOR", nullable = false))})
    public ActividadesExtracurricularesId getId() {
        return this.id;
    }

    public void setId(ActividadesExtracurricularesId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PROFESOR", nullable = false, insertable = false, updatable = false)
    public Profesor getProfesor() {
        return this.profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    @Column(name = "VC_DIRECCION", nullable = false, length = 45)
    public String getVcDireccion() {
        return this.vcDireccion;
    }

    public void setVcDireccion(String vcDireccion) {
        this.vcDireccion = vcDireccion;
    }

    @Column(name = "VC_REFERENCIA", nullable = false, length = 45)
    public String getVcReferencia() {
        return this.vcReferencia;
    }

    public void setVcReferencia(String vcReferencia) {
        this.vcReferencia = vcReferencia;
    }

    @Column(name = "IN_NUMERO_CONTACTO", nullable = false)
    public int getInNumeroContacto() {
        return this.inNumeroContacto;
    }

    public void setInNumeroContacto(int inNumeroContacto) {
        this.inNumeroContacto = inNumeroContacto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_INICIO", nullable = false, length = 19)
    public Date getDtFechaInicio() {
        return this.dtFechaInicio;
    }

    public void setDtFechaInicio(Date dtFechaInicio) {
        this.dtFechaInicio = dtFechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_RETORNO", nullable = false, length = 19)
    public Date getDtFechaRetorno() {
        return this.dtFechaRetorno;
    }

    public void setDtFechaRetorno(Date dtFechaRetorno) {
        this.dtFechaRetorno = dtFechaRetorno;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION", length = 19)
    public Date getDtFechaCreacion() {
        return this.dtFechaCreacion;
    }

    public void setDtFechaCreacion(Date dtFechaCreacion) {
        this.dtFechaCreacion = dtFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION", length = 19)
    public Date getDtFechaModificacion() {
        return this.dtFechaModificacion;
    }

    public void setDtFechaModificacion(Date dtFechaModificacion) {
        this.dtFechaModificacion = dtFechaModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "actividadesExtracurriculares")
    public Set<IncidenciasPorActividadesExtracurriculares> getIncidenciasPorActividadesExtracurriculareses() {
        return this.incidenciasPorActividadesExtracurriculareses;
    }

    public void setIncidenciasPorActividadesExtracurriculareses(Set<IncidenciasPorActividadesExtracurriculares> incidenciasPorActividadesExtracurriculareses) {
        this.incidenciasPorActividadesExtracurriculareses = incidenciasPorActividadesExtracurriculareses;
    }

}
