package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Apoderado generated by hbm2java
 */
@Entity
@Table(name = "APODERADO"
)
public class Apoderado implements java.io.Serializable {

    private Integer idApoderado;
    private Persona persona;
    private Set<Alumno> alumnos = new HashSet(0);

    private TipoApoderado tipoApoderado;
    public Apoderado() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_APODERADO", unique = true, nullable = false)
    public Integer getIdApoderado() {
        return this.idApoderado;
    }

    public void setIdApoderado(Integer idApoderado) {
        this.idApoderado = idApoderado;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PERSONA", nullable = false)
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "apoderado")
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }

    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_APODERADO", nullable=false)
    public TipoApoderado getTipoApoderado() {
        return this.tipoApoderado;
    }
    
    public void setTipoApoderado(TipoApoderado tipoApoderado) {
        this.tipoApoderado = tipoApoderado;
    }
}
