package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "ASISTENCIA"
)
public class Asistencia implements java.io.Serializable {

    private Integer idAsistencia;
    private CursoPorProfesor cursoPorProfesor;
    private String vcNombre;
    private boolean asistir;
    private boolean tardanza;
    private boolean justificado;
    private Date fechaCreacion;
    private Date fechaModificacion;

    public Asistencia() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_ASISTENCIA", unique = true, nullable = false)
    public Integer getIdAsistencia() {
        return this.idAsistencia;
    }

    public void setIdAsistencia(Integer idAsistencia) {
        this.idAsistencia = idAsistencia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_CURSO_POR_PROFESOR", nullable = false)
    public CursoPorProfesor getCursoPorProfesor() {
        return this.cursoPorProfesor;
    }

    public void setCursoPorProfesor(CursoPorProfesor cursoPorProfesor) {
        this.cursoPorProfesor = cursoPorProfesor;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    public String getVcNombre() {
        return this.vcNombre;
    }

    public void setVcNombre(String vcNombre) {
        this.vcNombre = vcNombre;
    }

    @Column(name = "TY_ASISTIR", nullable = false)
    public boolean isAsistir() {
        return this.asistir;
    }

    public void setAsistir(boolean asistir) {
        this.asistir = asistir;
    }

    @Column(name = "TY_TARDANZA", nullable = false)
    public boolean isTardanza() {
        return this.tardanza;
    }

    public void setTardanza(boolean tardanza) {
        this.tardanza = tardanza;
    }

    @Column(name = "TY_JUSTIFICADO", nullable = false)
    public boolean isJustificado() {
        return this.justificado;
    }

    public void setJustificado(boolean justificado) {
        this.justificado = justificado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION")
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION")
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

}
