package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "CURSO"
)
public class Curso implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_CURSO", unique = true, nullable = false)
    private Integer idCurso;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SECCION", nullable = false)
    private Seccion seccion;
    
    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    private String nombre;
    
    @Column(name = "VC_CREADO_POR", length = 45)
    private String creadoPor;
    
    @Column(name = "VC_MODIFICADO_POR", length = 45)
    private String modificadoPor;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_MODIFICACION")
    private Date fechaModificacion;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_CREACION")
    private Date fechaCreacion;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
    private Set<CursoPorProfesor> cursoPorProfesors = new HashSet(0);

   
    public Integer getIdCurso() {
        return this.idCurso;
    }

    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

    public Seccion getSeccion() {
        return this.seccion;
    }

    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCreadoPor() {
        return this.creadoPor;
    }

    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    public String getModificadoPor() {
        return this.modificadoPor;
    }

    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Set getCursoPorProfesors() {
        return this.cursoPorProfesors;
    }

    public void setCursoPorProfesors(Set cursoPorProfesors) {
        this.cursoPorProfesors = cursoPorProfesors;
    }

}
