package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "HORARIO"
)
public class Horario implements java.io.Serializable {

    private Integer idHorario;
    private Salon salon;
    private Date diaClases;
    private Date horaInicio;
    private Date horaFinal;
    private Set<CursoPorProfesor> cursoPorProfesores = new HashSet(0);

    public Horario() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_HORARIO", unique = true, nullable = false)
    public Integer getIdHorario() {
        return this.idHorario;
    }

    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SALON", nullable = false)
    public Salon getSalon() {
        return this.salon;
    }

    public void setSalon(Salon salon) {
        this.salon = salon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_DIA_CLASES", nullable = false)
    public Date getDtDiaClases() {
        return this.diaClases;
    }

    public void setDtDiaClases(Date dtDiaClases) {
        this.diaClases = dtDiaClases;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_HORA_INICIO", nullable = false)
    public Date getHoraInicio() {
        return this.horaInicio;
    }

    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_HORA_FINAL", nullable = false)
    public Date getHoraFinal() {
        return this.horaFinal;
    }

    public void setHoraFinal(Date horaFinal) {
        this.horaFinal = horaFinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
    public Set<CursoPorProfesor> getCursoPorProfesores() {
        return this.cursoPorProfesores;
    }

    public void setCursoPorProfesores(Set<CursoPorProfesor> cursoPorProfesores) {
        this.cursoPorProfesores = cursoPorProfesores;
    }

}
