package com.sigera.entidad;
// Generated 24/10/2015 08:59:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IncidenciasId generated by hbm2java
 */
@Embeddable
public class IncidenciasId  implements java.io.Serializable {


     private int idIncidencias;
     private int idAlumno;

    public IncidenciasId() {
    }

    public IncidenciasId(int idIncidencias, int idAlumno) {
       this.idIncidencias = idIncidencias;
       this.idAlumno = idAlumno;
    }
   


    @Column(name="ID_INCIDENCIAS", nullable=false)
    public int getIdIncidencias() {
        return this.idIncidencias;
    }
    
    public void setIdIncidencias(int idIncidencias) {
        this.idIncidencias = idIncidencias;
    }


    @Column(name="ID_ALUMNO", nullable=false)
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IncidenciasId) ) return false;
		 IncidenciasId castOther = ( IncidenciasId ) other; 
         
		 return (this.getIdIncidencias()==castOther.getIdIncidencias())
 && (this.getIdAlumno()==castOther.getIdAlumno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIncidencias();
         result = 37 * result + this.getIdAlumno();
         return result;
   }   


}


