package com.sigera.entidad;
// Generated 24/10/2015 08:59:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IncidenciasPorActividadesExtracurricularesId generated by hbm2java
 */
@Embeddable
public class IncidenciasPorActividadesExtracurricularesId  implements java.io.Serializable {


     private int idIncidenciasPorActividadesExtracurriculares;
     private int idIncidencias;
     private int idAlumno;
     private int idActividadesExtracurriculares;
     private int idProfesor;

    public IncidenciasPorActividadesExtracurricularesId() {
    }

    public IncidenciasPorActividadesExtracurricularesId(int idIncidenciasPorActividadesExtracurriculares, int idIncidencias, int idAlumno, int idActividadesExtracurriculares, int idProfesor) {
       this.idIncidenciasPorActividadesExtracurriculares = idIncidenciasPorActividadesExtracurriculares;
       this.idIncidencias = idIncidencias;
       this.idAlumno = idAlumno;
       this.idActividadesExtracurriculares = idActividadesExtracurriculares;
       this.idProfesor = idProfesor;
    }
   


    @Column(name="ID_INCIDENCIAS_POR_ACTIVIDADES_EXTRACURRICULARES", nullable=false)
    public int getIdIncidenciasPorActividadesExtracurriculares() {
        return this.idIncidenciasPorActividadesExtracurriculares;
    }
    
    public void setIdIncidenciasPorActividadesExtracurriculares(int idIncidenciasPorActividadesExtracurriculares) {
        this.idIncidenciasPorActividadesExtracurriculares = idIncidenciasPorActividadesExtracurriculares;
    }


    @Column(name="ID_INCIDENCIAS", nullable=false)
    public int getIdIncidencias() {
        return this.idIncidencias;
    }
    
    public void setIdIncidencias(int idIncidencias) {
        this.idIncidencias = idIncidencias;
    }


    @Column(name="ID_ALUMNO", nullable=false)
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }


    @Column(name="ID_ACTIVIDADES_EXTRACURRICULARES", nullable=false)
    public int getIdActividadesExtracurriculares() {
        return this.idActividadesExtracurriculares;
    }
    
    public void setIdActividadesExtracurriculares(int idActividadesExtracurriculares) {
        this.idActividadesExtracurriculares = idActividadesExtracurriculares;
    }


    @Column(name="ID_PROFESOR", nullable=false)
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IncidenciasPorActividadesExtracurricularesId) ) return false;
		 IncidenciasPorActividadesExtracurricularesId castOther = ( IncidenciasPorActividadesExtracurricularesId ) other; 
         
		 return (this.getIdIncidenciasPorActividadesExtracurriculares()==castOther.getIdIncidenciasPorActividadesExtracurriculares())
 && (this.getIdIncidencias()==castOther.getIdIncidencias())
 && (this.getIdAlumno()==castOther.getIdAlumno())
 && (this.getIdActividadesExtracurriculares()==castOther.getIdActividadesExtracurriculares())
 && (this.getIdProfesor()==castOther.getIdProfesor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIncidenciasPorActividadesExtracurriculares();
         result = 37 * result + this.getIdIncidencias();
         result = 37 * result + this.getIdAlumno();
         result = 37 * result + this.getIdActividadesExtracurriculares();
         result = 37 * result + this.getIdProfesor();
         return result;
   }   


}


