package com.sigera.entidad;
// Generated 24/10/2015 08:59:36 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IncidenciasPorActividadesExtracurriculares generated by hbm2java
 */
@Entity
@Table(name = "INCIDENCIAS_POR_ACTIVIDADES_EXTRACURRICULARES"
)
public class IncidenciasPorActividadesExtracurriculares implements java.io.Serializable {

    private IncidenciasPorActividadesExtracurricularesId id;
    private ActividadesExtracurriculares actividadesExtracurriculares;
    private Incidencias incidencias;

    public IncidenciasPorActividadesExtracurriculares() {
    }

    public IncidenciasPorActividadesExtracurriculares(IncidenciasPorActividadesExtracurricularesId id, ActividadesExtracurriculares actividadesExtracurriculares, Incidencias incidencias) {
        this.id = id;
        this.actividadesExtracurriculares = actividadesExtracurriculares;
        this.incidencias = incidencias;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idIncidenciasPorActividadesExtracurriculares", column = @Column(name = "ID_INCIDENCIAS_POR_ACTIVIDADES_EXTRACURRICULARES", nullable = false)),
        @AttributeOverride(name = "idIncidencias", column = @Column(name = "ID_INCIDENCIAS", nullable = false)),
        @AttributeOverride(name = "idAlumno", column = @Column(name = "ID_ALUMNO", nullable = false)),
        @AttributeOverride(name = "idActividadesExtracurriculares", column = @Column(name = "ID_ACTIVIDADES_EXTRACURRICULARES", nullable = false)),
        @AttributeOverride(name = "idProfesor", column = @Column(name = "ID_PROFESOR", nullable = false))})
    public IncidenciasPorActividadesExtracurricularesId getId() {
        return this.id;
    }

    public void setId(IncidenciasPorActividadesExtracurricularesId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "ID_ACTIVIDADES_EXTRACURRICULARES", referencedColumnName = "ID_ACTIVIDADES_EXTRACURRICULARES", nullable = false, insertable = false, updatable = false),
        @JoinColumn(name = "ID_PROFESOR", referencedColumnName = "ID_PROFESOR", nullable = false, insertable = false, updatable = false)})
    public ActividadesExtracurriculares getActividadesExtracurriculares() {
        return this.actividadesExtracurriculares;
    }

    public void setActividadesExtracurriculares(ActividadesExtracurriculares actividadesExtracurriculares) {
        this.actividadesExtracurriculares = actividadesExtracurriculares;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "ID_INCIDENCIAS", referencedColumnName = "ID_INCIDENCIAS", nullable = false, insertable = false, updatable = false),
        @JoinColumn(name = "ID_ALUMNO", referencedColumnName = "ID_ALUMNO", nullable = false, insertable = false, updatable = false)})
    public Incidencias getIncidencias() {
        return this.incidencias;
    }

    public void setIncidencias(Incidencias incidencias) {
        this.incidencias = incidencias;
    }

}
