package com.sigera.entidad;
// Generated 24/10/2015 08:59:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Incidencias generated by hbm2java
 */
@Entity
@Table(name = "INCIDENCIAS"
)
public class Incidencias implements java.io.Serializable {

    private IncidenciasId id;
    private Alumno alumno;
    private TipoIncidencia tipoIncidencia;
    private String vcDescripcion;
    private Date dtFechaIncidencia;
    private Date dtFechaRegistro;
    private Set<IncidenciasPorActividadesExtracurriculares> incidenciasPorActividadesExtracurriculareses = new HashSet(0);

    public Incidencias() {
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idIncidencias", column = @Column(name = "ID_INCIDENCIAS", nullable = false)),
        @AttributeOverride(name = "idAlumno", column = @Column(name = "ID_ALUMNO", nullable = false))})
    public IncidenciasId getId() {
        return this.id;
    }

    public void setId(IncidenciasId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ALUMNO", nullable = false, insertable = false, updatable = false)
    public Alumno getAlumno() {
        return this.alumno;
    }

    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_TIPO_INCIDENCIA", nullable = false)
    public TipoIncidencia getTipoIncidencia() {
        return this.tipoIncidencia;
    }

    public void setTipoIncidencia(TipoIncidencia tipoIncidencia) {
        this.tipoIncidencia = tipoIncidencia;
    }

    @Column(name = "VC_DESCRIPCION", nullable = false, length = 555)
    public String getVcDescripcion() {
        return this.vcDescripcion;
    }

    public void setVcDescripcion(String vcDescripcion) {
        this.vcDescripcion = vcDescripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_INCIDENCIA", nullable = false, length = 19)
    public Date getDtFechaIncidencia() {
        return this.dtFechaIncidencia;
    }

    public void setDtFechaIncidencia(Date dtFechaIncidencia) {
        this.dtFechaIncidencia = dtFechaIncidencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DT_FECHA_REGISTRO", length = 19)
    public Date getDtFechaRegistro() {
        return this.dtFechaRegistro;
    }

    public void setDtFechaRegistro(Date dtFechaRegistro) {
        this.dtFechaRegistro = dtFechaRegistro;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "incidencias")
    public Set<IncidenciasPorActividadesExtracurriculares> getIncidenciasPorActividadesExtracurriculareses() {
        return this.incidenciasPorActividadesExtracurriculareses;
    }

    public void setIncidenciasPorActividadesExtracurriculareses(Set<IncidenciasPorActividadesExtracurriculares> incidenciasPorActividadesExtracurriculareses) {
        this.incidenciasPorActividadesExtracurriculareses = incidenciasPorActividadesExtracurriculareses;
    }

}
