package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "PERFIL"
)
public class Perfil implements java.io.Serializable {

    public Perfil() {
    }

    @Id
    @GeneratedValue

    @Column(name = "ID_PERFIL")
    Integer id;

     

    @Column(name = "VC_NOMBRE", nullable = false)
    String nombre;
    
    @Column(name = "TY_ESTADO", nullable = false)
    boolean estado;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
    Set<Usuario> usuarios = new HashSet<Usuario>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil", cascade = CascadeType.ALL)
    Set<Permiso> permisos = new HashSet<Permiso>(0);

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<Usuario> getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    public Set<Permiso> getPermisos() {
        return permisos;
    }

    public void setPermisos(Set<Permiso> permisos) {
        this.permisos = permisos;
    }

}
