package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recibo generated by hbm2java
 */
@Entity
@Table(name="RECIBO"
    
)
public class Recibo  implements java.io.Serializable {


     private Integer idRecibo;
     private Alumno alumno;
     private TipoPago tipoPago;
     private double subtotal;
     private double igv;
     private double mora;
     private double total;
     private Date fechaEmision;

    public Recibo() {
    }

	
   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_RECIBO", unique=true, nullable=false)
    public Integer getIdRecibo() {
        return this.idRecibo;
    }
    
    public void setIdRecibo(Integer idRecibo) {
        this.idRecibo = idRecibo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ALUMNO", nullable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_PAGO", nullable=false)
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }

    
    @Column(name="DB_SUBTOTAL", nullable=false, precision=22, scale=0)
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="DB_IGV", nullable=false, precision=22, scale=0)
    public double getIgv() {
        return this.igv;
    }
    
    public void setIgv(double igv) {
        this.igv = igv;
    }

    
    @Column(name="DB_MORA", nullable=false, precision=22, scale=0)
    public double getMora() {
        return this.mora;
    }
    
    public void setMora(double mora) {
        this.mora = mora;
    }

    
    @Column(name="DB_TOTAL", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_FECHA_EMISION")
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }




}


