package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoIncidencia generated by hbm2java
 */
@Entity
@Table(name = "TIPO_INCIDENCIA"
)
public class TipoIncidencia implements java.io.Serializable {

    private Integer idTipoIncidencia;
    private String nombre;
    private Set<Incidencias> incidencias = new HashSet(0);

    public TipoIncidencia() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_TIPO_INCIDENCIA", unique = true, nullable = false)
    public Integer getIdTipoIncidencia() {
        return this.idTipoIncidencia;
    }

    public void setIdTipoIncidencia(Integer idTipoIncidencia) {
        this.idTipoIncidencia = idTipoIncidencia;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 100)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIncidencia")
    public Set<Incidencias> getIncidencias() {
        return this.incidencias;
    }

    public void setIncidencias(Set<Incidencias> incidencias) {
        this.incidencias = incidencias;
    }

}
