package com.sigera.entidad;
// Generated 07/10/2015 04:43:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAlumno generated by hbm2java
 */
@Entity
@Table(name = "TIPO_ALUMNO"
)
public class TipoAlumno implements java.io.Serializable {

    private Integer idTipoAlumno;
    private String nombre;
    private Set<Alumno> alumnos = new HashSet(0);

    public TipoAlumno() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID_TIPO_ALUMNO", unique = true, nullable = false)
    public Integer getIdTipoAlumno() {
        return this.idTipoAlumno;
    }

    public void setIdTipoAlumno(Integer idTipoAlumno) {
        this.idTipoAlumno = idTipoAlumno;
    }

    @Column(name = "VC_NOMBRE", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAlumno")
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }

    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }

}
