package com.sigera.entidad;
// Generated 24/10/2015 08:59:36 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoApoderado generated by hbm2java
 */
@Entity
@Table(name = "TIPO_APODERADO"
)
public class TipoApoderado implements java.io.Serializable {

    private int idTipoApoderado;
    private String vcDescripcion;
    private Set<Apoderado> apoderados = new HashSet(0);

    public TipoApoderado() {
    }

    @Id

    @Column(name = "ID_TIPO_APODERADO", unique = true, nullable = false)
    public int getIdTipoApoderado() {
        return this.idTipoApoderado;
    }

    public void setIdTipoApoderado(int idTipoApoderado) {
        this.idTipoApoderado = idTipoApoderado;
    }

    @Column(name = "VC_DESCRIPCION", nullable = false, length = 100)
    public String getVcDescripcion() {
        return this.vcDescripcion;
    }

    public void setVcDescripcion(String vcDescripcion) {
        this.vcDescripcion = vcDescripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoApoderado")
    public Set<Apoderado> getApoderados() {
        return this.apoderados;
    }

    public void setApoderados(Set<Apoderado> apoderados) {
        this.apoderados = apoderados;
    }

}
